services:
  backend:
    image: ghcr.io/gregory1175/film-react-nest/backend:latest
    container_name: backend
    depends_on:
      - postgres
    networks:
      - postgres_network
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    image: ghcr.io/gregory1175/film-react-nest/frontend:latest
    container_name: frontend
    networks:
      - postgres_network
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - frontend/.env

  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - postgres_network
    env_file:
      - /.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - postgres_network
    env_file:
      - /.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - postgres_network
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - frontend_dist:/var/www/frontend:ro

  certbot:
    image: certbot/certbot:latest
    networks:
      - postgres_network
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  postgres_network:

volumes:
  postgres-data:
  pgadmin-data:
  frontend_dist: