services:
  database:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - internet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - internet

  frontend:
    image: "ghcr.io/${OWNER}/sp16_frontend:latest"
    build:
      context: frontend
    environment:
      VITE_BAE_URL: /
      VITE_API_URL: /api/afisha
      VITE_CDN_URL: /content/afisha
    volumes:
      - frontend_build:/app/dist

  backend:
    image: "ghcr.io/${OWNER}/sp16_backend:latest"
    build:
      context: backend
    environment:
      PORT: 3000
      DEBUG: "*"
      DATABASE_DRIVER: "postgres"
      DATABASE_URL: "postgres://database:5432/${DB_NAME}"
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3000:3000
    networks:
      - internet
    depends_on:
      - database

  server:
    image: "ghcr.io/${OWNER}/sp16_server:latest"
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - frontend_build:/var/www
    depends_on:
      - frontend
      - backend
    networks:
      - internet

volumes:
  db_data:
  pgadmin-data:
  frontend_build:

networks:
  internet:
